# Generated by Django 5.2 on 2025-05-06 01:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vendedor_ordencompracliente_itemordencompracliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('tipo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
            ],
            options={
                'db_table': 'tipos_identificacion',
                'ordering': ['nombre_tipo'],
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clientes_tipo_identificacion', to='core.tipoidentificacion'),
        ),
    ]
